Vagrant.configure("2") do |config|
  #>>>>>>first mashine
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-22.04"
    ubuntu.vm.hostname = "vgubuntu"
    ubuntu.vm.network "public_network", type: "dhcp"

    ubuntu.vm.provider "virtualbox" do |vb|
      # customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 1
    end

    ubuntu.vm.provision "shell", inline: <<-SHELL
      #commands
      sudo useradd --system --no-create-home --shell /bin/false prometheus
      wget https://github.com/prometheus/prometheus/releases/download/v2.32.1/prometheus-2.32.1.linux-amd64.tar.gz
      tar -xvf prometheus-2.32.1.linux-amd64.tar.gz
      sudo mkdir -p /data /etc/prometheus
      cd prometheus-2.32.1.linux-amd64
      sudo mv prometheus promtool /usr/local/bin/
      sudo mv consoles/ console_libraries/ /etc/prometheus/
      sudo mv prometheus.yml /etc/prometheus/prometheus.yml
      cd ~
      sudo chown -R prometheus:prometheus /etc/prometheus/ /data/
      rm -rf prometheus*
      sudo touch /etc/systemd/system/prometheus.service

      cat <<EOL > /etc/systemd/system/prometheus.service
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

StartLimitIntervalSec=500
StartLimitBurst=5

[Service]
User=prometheus
Group=prometheus
Type=simple
Restart=on-failure
RestartSec=5s
ExecStart=/usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path=/data \
  --web.console.templates=/etc/prometheus/consoles \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.listen-address=0.0.0.0:9090 \
  --web.enable-lifecycle

[Install]
WantedBy=multi-user.target
EOL
    SHELL
  end

  #>>>>>> second mashine
  config.vm.define "centos" do |centos|
    centos.vm.box = "bento/centos-7"
    centos.vm.hostname = "vgcentos"
    centos.vm.network "public_network", type: "dhcp"

    centos.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 1
    end

    centos.vm.provision "shell", inline: <<-SHELL
      cd /tmp
      sudo yum update -y
      sudo yum install -y wget
      sudo wget https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
      sudo tar xvfz node_exporter-1.4.0.linux-amd64.tar.gz
      sudo mv node_exporter-*.*-amd64/node_exporter /usr/local/bin/
      sudo useradd -rs /bin/false node_exporter
      sudo touch /etc/systemd/system/node_exporter.service

      cat <<EOL > /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=node_exporter
Group=node_exporter
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOL
    SHELL
  end

    #>>>>>> third mashine
  config.vm.define "debian" do |debian|
    debian.vm.box = "bento/debian-12.1"
    debian.vm.hostname = "vgdebian"
    debian.vm.network "public_network", type: "dhcp"
    
    config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 1
    end

    debian.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y wget
      wget https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
      tar xvfz node_exporter-1.4.0.linux-amd64.tar.gz
      sudo mv node_exporter-*.*-amd64/node_exporter /usr/local/bin/
      sudo useradd -rs /bin/false node_exporter
      sudo touch /etc/systemd/system/node_exporter.service

      cat <<EOL > /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=node_exporter
Group=node_exporter
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOL

      systemctl daemon-reload
      systemctl enable node_exporter
      systemctl start node_exporter
    SHELL
  end

  #>>>>>> third mashine
  config.vm.define "debian" do |debian|
    debian.vm.box = "bento/debian-12.1"
    debian.vm.hostname = "vgdebian"
    debian.vm.network "public_network", type: "dhcp"
    
    config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 1
    end

    debian.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y wget
      wget https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
      tar xvfz node_exporter-1.4.0.linux-amd64.tar.gz
      sudo mv node_exporter-*.*-amd64/node_exporter /usr/local/bin/
      sudo useradd -rs /bin/false node_exporter
      sudo touch /etc/systemd/system/node_exporter.service

      cat <<EOL > /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=node_exporter
Group=node_exporter
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOL

      systemctl daemon-reload
      systemctl enable node_exporter
      systemctl start node_exporter
    SHELL
  end
end
